CREATE TABLE IF NOT EXISTS USERS (
    id    BIGINT AUTO_INCREMENT PRIMARY KEY,
    name  VARCHAR(50)  NOT NULL,
    email VARCHAR(100) NOT NULL,
    age   INT          NOT NULL,
    city  VARCHAR(50)  NOT NULL
);